export const FETCH_PROVIDERS = "FETCH_PROVIDERS";
export const PROVIDERS_LOADING = "PROVIDERS_LOADING";
export const PROVIDERS_FAILED = "PROVIDERS_FAILED";

export const FETCH_MESSAGES = "FETCH_MESSAGES";
export const MESSAGES_LOADING = "MESSAGES_LOADING";
export const MESSAGES_FAILED = "MESSAGES_FAILED";

export const FETCH_GROUPS = "FETCH_GROUPS";
export const ADD_GROUPS = "ADD_GROUPS";
export const GROUPS_LOADING = "GROUPS_LOADING";
export const GROUPS_FAILED = "GROUPS_FAILED";

export const FETCH_CURGROUP = "FETCH_CURGROUP";
export const ADD_CURGROUP = "ADD_CURGROUP";
export const CURGROUP_LOADING = "CURGROUP_LOADING";
export const CURGROUP_FAILED = "CURGROUP_FAILED";

export const FETCH_CURUSER = "FETCH_CURUSER";
export const ADD_CURUSER = "ADD_CURUSER";
export const CURUSER_LOADING = "CURUSER_LOADING";
export const CURUSER_FAILED = "CURUSER_FAILED";
export const REMOVE_CURUSER = "REMOVE_CURUSER";
